### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by natedogith1** [adamsong/SquidBot#1]
This is more of a code review.  The things listed here are largely for thinking about which way makes more sense to do things.

In SquidMain:
* createClient isn't indented correctly

In SquidEventHandler
* for onPresenceUpdate, you should probably use `getPresence().getStatus() == StatusType.OFFLINE` instead of a string compare
* for `/add global_game`, would it be better to use a role as a permission group instead of a permission?
* magic numbers are generally bad (19, for checking if game already exists).  maybe add a field/method to the SquidDB? (which could either be magic-number configured or read from `org.sqlite.core.Codes` using reflection)
* should GUILD_ID be a hard-coded value? (don't know how you'd get around this, maybe a config file/constants class?)
* should roles be statically configured IDs, or should the IDs be queried from the server?
* should the channels be matched by name or ID (only asking because roles are matched by ID)
* with all the appending you're doing, you might want to use StringBuilder (just because it's supposed to be better for such things)

In SquidDB:
* the constructor is doing some weird string joins (looks like an improper auto-formatter)
* for getGame and addGlobalGame, proper convention would have them taking strings (or at the very least, not assuming that the array they're passed will need the first two arguments removed)
* just because I ran across it, you could make the temp table also a virtual table (just because I ran across it)
* should the SquidEventHandler have to deal with the `create temp table -> add users -> get info -> remove temp table` calls or should their be a get info method that takes a threshold and a list of string
* the getCommonGames threshold could be handled on the SQL side instead of the java side.

**Comment by adamsong** [comment]
I started Pull Request #2 with my changes based on this, I will also address all of your points here to explain my actions based on each of them

In SquidMain
- I am not sure what you meant by improperly indented, I ran the formatter but did not notice much change beyond the comments being line wrapped

In SquidEventHandler
- I was unaware the comparison could be done this way, looked for it when the comparison was originally written but could not find it, updated to compare the Enums
- My logic behind using the permission was it is a permission that does not make a big impact when given to admins, allowing other roles to be set to allow or disallow adding of games. A role would work just as well probably
- I changed the 19 to use the constant in `org.sqlite.core.Codes`, no reflection necessary
- I moved all of my constants into the Constants file, it means they aren't on github anymore but they are all in the same place if they need to be changed. I did not write this with portability in mind, and getting a guild id from the discord client is trivial
- I could query for all roles with the name, but that gives a list and in the event there are more than one I might pick the wrong one. To combat this I simply grabbed the IDs from the client, and put them in constants for easy config.
- Checking the channel is easier because I can just grab a name from the object and do a string compare rather than pulling a list.
- Because you seemed unsure about which is faster I did a quick google and google seemed unhelpful so [https://gist.github.com/adamsong/6fb3bf74bf12c4c77a3afa8b20707788](I did my own test). I have moved over to string builder.

In SquidDB
- You are correct about the auto-formatter, fixed
- I moved the array item remover and joiner line from getGame and addGlobalGame and added it to the calling methods
- I find little benefit to the virtual table accompanied by having to change code that works for code that might not work did not seem very appealing
- I have left the methods alone, while adding a single method to handle everything 
- I was unable to get the SQL threshold working when that was written, I managed to get it to work however and have implemented the change

**Comment by natedogith1** [comment]
For checking channel via name vs id.  Checking by name is easy.  But you wouldn't need to pull the list.  IChannel extends IIDLinkedObject, which has the getLongID() method.

**Comment by adamsong** [comment]
If I do that I still have to get an ID to compare to, rather than just knowing the name.
